package com.zheng.bibackend.model.vo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @Author: Zheng Zhang
 * @Description
 * @Created 08/06/2023 - 22:17
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
public class BiResponse {
  
  /**
   * Chart data generated by AI.
   */
  private String genChart;
  
  /**
   * Chart result generated by AI.
   */
  private String genResult;
  
  /**
   * Chart ID.
   */
  private long chartId;
}
