spring:
  application:
    name: user-center
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_db
    username: root
    password: zz2843517195
  # session expiration time(minutes): two months
  session:
    timeout: 86400
    redis:
      repository-type: default
  # redis config
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
springdoc:
  swagger-ui:
    path: /docs-home.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zheng.bibackend.controller
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        max-age: 2592000
#  servlet:
#    context-path: /api
#    session:
#      cookie:
#        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0